// Copyright 2020-2021 Extreme Networks, Inc.
// All rights reserved.

// This file is auto-generated via /npb-dp/p4_pipelines/cls/pipeline.py
#ifndef _DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY_EGONLY_
#define _DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY_EGONLY_

// Use this #define within your modules to declare
// the list of deployment parameters being passed in
// from above.
#define MODULE_DEPLOYMENT_PARAMS \
bool TRANSPORT_INGRESS_ENABLE = true, \
bool TRANSPORT_EGRESS_ENABLE = true, \
bool TRANSPORT_IPV4_INGRESS_ENABLE = true, \
bool TRANSPORT_IPV4_EGRESS_ENABLE = true, \
bool TRANSPORT_IPV6_INGRESS_ENABLE = true, \
bool TRANSPORT_IPV6_EGRESS_ENABLE = true, \
bool TRANSPORT_IPV6_REDUCED_ADDR = true, \
bool TRANSPORT_GRE_INGRESS_ENABLE = true, \
bool TRANSPORT_GRE_EGRESS_ENABLE = true, \
bool TRANSPORT_ERSPAN_INGRESS_ENABLE = true, \
bool TRANSPORT_ERSPAN_EGRESS_ENABLE = true, \
bool TRANSPORT_ERSPAN_INGRESS_SET_TUNNEL_ID = false, \
bool TRANSPORT_IPV4_VXLAN_INGRESS_ENABLE = true, \
bool TRANSPORT_IPV4_GENEVE_INGRESS_ENABLE = false, \
bool TRANSPORT_SPBM_INGRESS_ENABLE = true, \
bool TRANSPORT_EoMPLS_INGRESS_ENABLE = false, \
bool TRANSPORT_IPoMPLS_INGRESS_ENABLE = true, \
bool OUTER_ETAG_ENABLE = true, \
bool OUTER_VNTAG_ENABLE = true, \
bool OUTER_EoMPLS_ENABLE = false, \
bool OUTER_EoMPLS_PWCW_ENABLE = false, \
bool OUTER_IPoMPLS_ENABLE = false, \
bool OUTER_MPLSoGRE_ENABLE = false, \
bool OUTER_IPV6_ENABLE = true, \
bool OUTER_IPINIP_ENABLE = true, \
bool OUTER_GENEVE_ENABLE = false, \
bool OUTER_VXLAN_ENABLE = true, \
bool OUTER_NVGRE_ENABLE = true, \
bool OUTER_GRE_ENABLE = true, \
bool OUTER_GTP_ENABLE = true, \
bool INNER_IPV6_ENABLE = true, \
bool INNER_IPINIP_ENABLE = true, \
bool INNER_GRE_ENABLE = true, \
bool INNER_GTP_ENABLE = true, \
bool INNER_INNER_IPV6_ENABLE = true, \
bool UDF_ENABLE = false, \
bool FOLDED_ENABLE = false, \
bool INGRESS_ENABLE = true, \
bool EGRESS_ENABLE = false, \
bit<32> MPLS_DEPTH_TRANSPORT = 4, \
bit<32> MPLS_DEPTH_OUTER = 4, \
bit<32> PORT_TABLE_SIZE = 288, \
bit<32> VLAN_TABLE_SIZE = 4096, \
bit<32> PORT_VLAN_TABLE_SIZE = 1024, \
bit<32> BD_TABLE_SIZE = 5120, \
bit<32> RMAC_TABLE_SIZE = 64, \
bit<32> MAC_TABLE_SIZE = 1024, \
bit<32> IPV4_DST_TUNNEL_TABLE_SIZE = 1024, \
bit<32> IPV4_SRC_TUNNEL_TABLE_SIZE = 256, \
bit<32> IPV6_DST_TUNNEL_TABLE_SIZE = 1024, \
bit<32> IPV6_SRC_TUNNEL_TABLE_SIZE = 256, \
bit<32> TUNNEL_SRC_REWRITE_TABLE_SIZE = 512, \
bit<32> TUNNEL_DST_REWRITE_TABLE_SIZE = 1024, \
bit<32> TUNNEL_SMAC_REWRITE_TABLE_SIZE = 32, \
bit<32> TUNNEL_DMAC_REWRITE_TABLE_SIZE = 256, \
bit<32> NEXTHOP_TABLE_SIZE = 8192, \
bit<32> ECMP_GROUP_TABLE_SIZE = 1024, \
bit<32> ECMP_SELECT_TABLE_SIZE = 16384, \
bit<32> OUTER_NEXTHOP_TABLE_SIZE = 4096, \
bit<32> OUTER_ECMP_GROUP_TABLE_SIZE = 4096, \
bit<32> OUTER_ECMP_SELECT_TABLE_SIZE = 16384, \
bit<32> LAG_TABLE_SIZE = 1024, \
bit<32> LAG_GROUP_TABLE_SIZE = 32, \
bit<32> LAG_MAX_MEMBERS_PER_GROUP = 64, \
bit<32> LAG_SELECTOR_TABLE_SIZE = 2048, \
bit<32> INGRESS_MAC_ACL_TABLE_SIZE = 1536, \
bit<32> INGRESS_IPV4_ACL_TABLE_SIZE = 6144, \
bit<32> INGRESS_IPV6_ACL_TABLE_SIZE = 2048, \
bit<32> INGRESS_L7_ACL_TABLE_SIZE = 1024, \
bit<32> EGRESS_MAC_ACL_TABLE_SIZE = 2048, \
bit<32> EGRESS_IPV4_ACL_TABLE_SIZE = 6144, \
bit<32> EGRESS_IPV6_ACL_TABLE_SIZE = 2048, \
bit<32> INGRESS_IP_DTEL_ACL_TABLE_SIZE = 512, \
bit<32> DTEL_GROUP_TABLE_SIZE = 4, \
bit<32> DTEL_MAX_MEMBERS_PER_GROUP = 64, \
bit<32> DTEL_SELECTOR_TABLE_SIZE = 256, \
bit<32> NPB_ING_SFC_TUNNEL_NETWORK_SAP_TABLE_DEPTH = 8192, \
bit<32> NPB_ING_SFC_TUNNEL_OUTER_EXM_TABLE_DEPTH = 8192, \
bit<32> NPB_ING_SFC_TUNNEL_OUTER_TCAM_TABLE_DEPTH = 1024, \
bit<32> NPB_ING_SFC_TUNNEL_INNER_EXM_TABLE_DEPTH = 8192, \
bit<32> NPB_ING_SFC_TUNNEL_INNER_TCAM_TABLE_DEPTH = 2048, \
bit<32> NPB_ING_SFC_SF_SEL_TABLE_DEPTH = 8192, \
bit<32> NPB_ING_SFC_SF_SEL_NSH_XLATE_TABLE_DEPTH = 8192, \
bit<32> NPB_ING_SF_0_BAS_ADV_SFF_TABLE_DEPTH = 1024, \
bit<32> NPB_ING_SF_0_BAS_ADV_POLICY_L3_LEN_RNG_TABLE_DEPTH = 128, \
bit<32> NPB_ING_SF_0_BAS_ADV_POLICY_L4_SRC_RNG_TABLE_DEPTH = 256, \
bit<32> NPB_ING_SF_0_BAS_ADV_POLICY_L4_DST_RNG_TABLE_DEPTH = 256, \
bit<32> NPB_ING_SF_0_SFP_FLW_CLS_TABLE_DEPTH = 128, \
bit<32> NPB_ING_SF_0_SFP_SCHD_TABLE_SIZE = 8192, \
bit<32> NPB_ING_SF_0_SFP_SCHD_GROUP_TABLE_SIZE = 128, \
bit<32> NPB_ING_SF_0_SFP_SCHD_MAX_MEMBERS_PER_GROUP = 128, \
bit<32> NPB_ING_SF_0_SFP_SCHD_SELECTOR_TABLE_SIZE = 16384, \
bit<32> NPB_ING_SFF_ARP_TABLE_DEPTH = 8192, \
bit<32> NPB_ING_SF_1_MULTICAST_SFF_TABLE_DEPTH = 1024, \
bit<32> NPB_ING_SF_1_MULTICAST_RID_TABLE_SIZE = 2096, \
bit<32> NPB_EGR_SF_2_EGRESS_SFP_SFF_TABLE_DEPTH = 8192, \
bit<32> NPB_EGR_SF_2_EGRESS_SFP_POLICY_L3_LEN_RNG_TABLE_DEPTH = 128, \
bit<32> NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_SRC_RNG_TABLE_DEPTH = 256, \
bit<32> NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_DST_RNG_TABLE_DEPTH = 256, \
bit<32> NPB_EGR_SF_2_EGRESS_SFP_HDR_STRIP_TABLE_DEPTH = 8, \
bit<32> NPB_EGR_SF_2_EGRESS_SFP_TRUNC_TABLE_DEPTH = 8, \
bit<32> NPB_EGR_SFF_ARP_TABLE_DEPTH = 8192, \
bit<32> DEDUP_NUM_BLOCKS = 16, \
bit<32> DEDUP_ADDR_WIDTH = 16

// Use this #define within your modules to declare
// the list of deployment parameters being passed down
// to sub-module instances.
#define INSTANCE_DEPLOYMENT_PARAMS \
TRANSPORT_INGRESS_ENABLE, \
TRANSPORT_EGRESS_ENABLE, \
TRANSPORT_IPV4_INGRESS_ENABLE, \
TRANSPORT_IPV4_EGRESS_ENABLE, \
TRANSPORT_IPV6_INGRESS_ENABLE, \
TRANSPORT_IPV6_EGRESS_ENABLE, \
TRANSPORT_IPV6_REDUCED_ADDR, \
TRANSPORT_GRE_INGRESS_ENABLE, \
TRANSPORT_GRE_EGRESS_ENABLE, \
TRANSPORT_ERSPAN_INGRESS_ENABLE, \
TRANSPORT_ERSPAN_EGRESS_ENABLE, \
TRANSPORT_ERSPAN_INGRESS_SET_TUNNEL_ID, \
TRANSPORT_IPV4_VXLAN_INGRESS_ENABLE, \
TRANSPORT_IPV4_GENEVE_INGRESS_ENABLE, \
TRANSPORT_SPBM_INGRESS_ENABLE, \
TRANSPORT_EoMPLS_INGRESS_ENABLE, \
TRANSPORT_IPoMPLS_INGRESS_ENABLE, \
OUTER_ETAG_ENABLE, \
OUTER_VNTAG_ENABLE, \
OUTER_EoMPLS_ENABLE, \
OUTER_EoMPLS_PWCW_ENABLE, \
OUTER_IPoMPLS_ENABLE, \
OUTER_MPLSoGRE_ENABLE, \
OUTER_IPV6_ENABLE, \
OUTER_IPINIP_ENABLE, \
OUTER_GENEVE_ENABLE, \
OUTER_VXLAN_ENABLE, \
OUTER_NVGRE_ENABLE, \
OUTER_GRE_ENABLE, \
OUTER_GTP_ENABLE, \
INNER_IPV6_ENABLE, \
INNER_IPINIP_ENABLE, \
INNER_GRE_ENABLE, \
INNER_GTP_ENABLE, \
INNER_INNER_IPV6_ENABLE, \
UDF_ENABLE, \
FOLDED_ENABLE, \
INGRESS_ENABLE, \
EGRESS_ENABLE, \
MPLS_DEPTH_TRANSPORT, \
MPLS_DEPTH_OUTER, \
PORT_TABLE_SIZE, \
VLAN_TABLE_SIZE, \
PORT_VLAN_TABLE_SIZE, \
BD_TABLE_SIZE, \
RMAC_TABLE_SIZE, \
MAC_TABLE_SIZE, \
IPV4_DST_TUNNEL_TABLE_SIZE, \
IPV4_SRC_TUNNEL_TABLE_SIZE, \
IPV6_DST_TUNNEL_TABLE_SIZE, \
IPV6_SRC_TUNNEL_TABLE_SIZE, \
TUNNEL_SRC_REWRITE_TABLE_SIZE, \
TUNNEL_DST_REWRITE_TABLE_SIZE, \
TUNNEL_SMAC_REWRITE_TABLE_SIZE, \
TUNNEL_DMAC_REWRITE_TABLE_SIZE, \
NEXTHOP_TABLE_SIZE, \
ECMP_GROUP_TABLE_SIZE, \
ECMP_SELECT_TABLE_SIZE, \
OUTER_NEXTHOP_TABLE_SIZE, \
OUTER_ECMP_GROUP_TABLE_SIZE, \
OUTER_ECMP_SELECT_TABLE_SIZE, \
LAG_TABLE_SIZE, \
LAG_GROUP_TABLE_SIZE, \
LAG_MAX_MEMBERS_PER_GROUP, \
LAG_SELECTOR_TABLE_SIZE, \
INGRESS_MAC_ACL_TABLE_SIZE, \
INGRESS_IPV4_ACL_TABLE_SIZE, \
INGRESS_IPV6_ACL_TABLE_SIZE, \
INGRESS_L7_ACL_TABLE_SIZE, \
EGRESS_MAC_ACL_TABLE_SIZE, \
EGRESS_IPV4_ACL_TABLE_SIZE, \
EGRESS_IPV6_ACL_TABLE_SIZE, \
INGRESS_IP_DTEL_ACL_TABLE_SIZE, \
DTEL_GROUP_TABLE_SIZE, \
DTEL_MAX_MEMBERS_PER_GROUP, \
DTEL_SELECTOR_TABLE_SIZE, \
NPB_ING_SFC_TUNNEL_NETWORK_SAP_TABLE_DEPTH, \
NPB_ING_SFC_TUNNEL_OUTER_EXM_TABLE_DEPTH, \
NPB_ING_SFC_TUNNEL_OUTER_TCAM_TABLE_DEPTH, \
NPB_ING_SFC_TUNNEL_INNER_EXM_TABLE_DEPTH, \
NPB_ING_SFC_TUNNEL_INNER_TCAM_TABLE_DEPTH, \
NPB_ING_SFC_SF_SEL_TABLE_DEPTH, \
NPB_ING_SFC_SF_SEL_NSH_XLATE_TABLE_DEPTH, \
NPB_ING_SF_0_BAS_ADV_SFF_TABLE_DEPTH, \
NPB_ING_SF_0_BAS_ADV_POLICY_L3_LEN_RNG_TABLE_DEPTH, \
NPB_ING_SF_0_BAS_ADV_POLICY_L4_SRC_RNG_TABLE_DEPTH, \
NPB_ING_SF_0_BAS_ADV_POLICY_L4_DST_RNG_TABLE_DEPTH, \
NPB_ING_SF_0_SFP_FLW_CLS_TABLE_DEPTH, \
NPB_ING_SF_0_SFP_SCHD_TABLE_SIZE, \
NPB_ING_SF_0_SFP_SCHD_GROUP_TABLE_SIZE, \
NPB_ING_SF_0_SFP_SCHD_MAX_MEMBERS_PER_GROUP, \
NPB_ING_SF_0_SFP_SCHD_SELECTOR_TABLE_SIZE, \
NPB_ING_SFF_ARP_TABLE_DEPTH, \
NPB_ING_SF_1_MULTICAST_SFF_TABLE_DEPTH, \
NPB_ING_SF_1_MULTICAST_RID_TABLE_SIZE, \
NPB_EGR_SF_2_EGRESS_SFP_SFF_TABLE_DEPTH, \
NPB_EGR_SF_2_EGRESS_SFP_POLICY_L3_LEN_RNG_TABLE_DEPTH, \
NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_SRC_RNG_TABLE_DEPTH, \
NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_DST_RNG_TABLE_DEPTH, \
NPB_EGR_SF_2_EGRESS_SFP_HDR_STRIP_TABLE_DEPTH, \
NPB_EGR_SF_2_EGRESS_SFP_TRUNC_TABLE_DEPTH, \
NPB_EGR_SFF_ARP_TABLE_DEPTH, \
DEDUP_NUM_BLOCKS, \
DEDUP_ADDR_WIDTH 

// Deployment Profile: igOnly
// -----------------------------------------------

const bool TRANSPORT_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_IPV4_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_IPV4_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_IPV6_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_IPV6_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_IPV6_REDUCED_ADDR_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_GRE_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_GRE_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_ERSPAN_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_ERSPAN_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_ERSPAN_INGRESS_SET_TUNNEL_ID_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bool TRANSPORT_IPV4_VXLAN_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_IPV4_GENEVE_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bool TRANSPORT_SPBM_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool TRANSPORT_EoMPLS_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bool TRANSPORT_IPoMPLS_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool OUTER_ETAG_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool OUTER_VNTAG_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool OUTER_EoMPLS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bool OUTER_EoMPLS_PWCW_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bool OUTER_IPoMPLS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bool OUTER_MPLSoGRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bool OUTER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool OUTER_IPINIP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool OUTER_GENEVE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bool OUTER_VXLAN_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool OUTER_NVGRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool OUTER_GRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool OUTER_GTP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool INNER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool INNER_IPINIP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool INNER_GRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool INNER_GTP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool INNER_INNER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool UDF_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bool FOLDED_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bool INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = true;
const bool EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = false;
const bit<32> MPLS_DEPTH_TRANSPORT_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 4;
const bit<32> MPLS_DEPTH_OUTER_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 4;
const bit<32> PORT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 288;
const bit<32> VLAN_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 4096;
const bit<32> PORT_VLAN_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> BD_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 5120;
const bit<32> RMAC_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 64;
const bit<32> MAC_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> IPV4_DST_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> IPV4_SRC_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 256;
const bit<32> IPV6_DST_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> IPV6_SRC_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 256;
const bit<32> TUNNEL_SRC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 512;
const bit<32> TUNNEL_DST_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> TUNNEL_SMAC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 32;
const bit<32> TUNNEL_DMAC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 256;
const bit<32> NEXTHOP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8192;
const bit<32> ECMP_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> ECMP_SELECT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 16384;
const bit<32> OUTER_NEXTHOP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 4096;
const bit<32> OUTER_ECMP_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 4096;
const bit<32> OUTER_ECMP_SELECT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 16384;
const bit<32> LAG_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> LAG_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 32;
const bit<32> LAG_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 64;
const bit<32> LAG_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 2048;
const bit<32> INGRESS_MAC_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1536;
const bit<32> INGRESS_IPV4_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 6144;
const bit<32> INGRESS_IPV6_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 2048;
const bit<32> INGRESS_L7_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> EGRESS_MAC_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 2048;
const bit<32> EGRESS_IPV4_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 6144;
const bit<32> EGRESS_IPV6_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 2048;
const bit<32> INGRESS_IP_DTEL_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 512;
const bit<32> DTEL_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 4;
const bit<32> DTEL_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 64;
const bit<32> DTEL_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 256;
const bit<32> NPB_ING_SFC_TUNNEL_NETWORK_SAP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8192;
const bit<32> NPB_ING_SFC_TUNNEL_OUTER_EXM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8192;
const bit<32> NPB_ING_SFC_TUNNEL_OUTER_TCAM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> NPB_ING_SFC_TUNNEL_INNER_EXM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8192;
const bit<32> NPB_ING_SFC_TUNNEL_INNER_TCAM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 2048;
const bit<32> NPB_ING_SFC_SF_SEL_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8192;
const bit<32> NPB_ING_SFC_SF_SEL_NSH_XLATE_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8192;
const bit<32> NPB_ING_SF_0_BAS_ADV_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> NPB_ING_SF_0_BAS_ADV_POLICY_L3_LEN_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 128;
const bit<32> NPB_ING_SF_0_BAS_ADV_POLICY_L4_SRC_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 256;
const bit<32> NPB_ING_SF_0_BAS_ADV_POLICY_L4_DST_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 256;
const bit<32> NPB_ING_SF_0_SFP_FLW_CLS_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 128;
const bit<32> NPB_ING_SF_0_SFP_SCHD_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8192;
const bit<32> NPB_ING_SF_0_SFP_SCHD_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 128;
const bit<32> NPB_ING_SF_0_SFP_SCHD_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 128;
const bit<32> NPB_ING_SF_0_SFP_SCHD_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 16384;
const bit<32> NPB_ING_SFF_ARP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8192;
const bit<32> NPB_ING_SF_1_MULTICAST_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 1024;
const bit<32> NPB_ING_SF_1_MULTICAST_RID_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 2096;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8192;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_POLICY_L3_LEN_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 128;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_SRC_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 256;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_DST_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 256;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_HDR_STRIP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_TRUNC_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8;
const bit<32> NPB_EGR_SFF_ARP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 8192;
const bit<32> DEDUP_NUM_BLOCKS_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 16;
const bit<32> DEDUP_ADDR_WIDTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY = 16;

// Use this #define to pass the list of deployment
// params into your top-level module instantiations.
#define INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY_EGONLY_IGONLY \
TRANSPORT_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_IPV4_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_IPV4_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_IPV6_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_IPV6_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_IPV6_REDUCED_ADDR_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_GRE_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_GRE_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_ERSPAN_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_ERSPAN_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_ERSPAN_INGRESS_SET_TUNNEL_ID_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_IPV4_VXLAN_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_IPV4_GENEVE_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_SPBM_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_EoMPLS_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TRANSPORT_IPoMPLS_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_ETAG_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_VNTAG_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_EoMPLS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_EoMPLS_PWCW_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_IPoMPLS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_MPLSoGRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_IPINIP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_GENEVE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_VXLAN_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_NVGRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_GRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_GTP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INNER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INNER_IPINIP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INNER_GRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INNER_GTP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INNER_INNER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
UDF_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
FOLDED_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
MPLS_DEPTH_TRANSPORT_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
MPLS_DEPTH_OUTER_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
PORT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
VLAN_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
PORT_VLAN_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
BD_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
RMAC_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
MAC_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
IPV4_DST_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
IPV4_SRC_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
IPV6_DST_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
IPV6_SRC_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TUNNEL_SRC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TUNNEL_DST_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TUNNEL_SMAC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
TUNNEL_DMAC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NEXTHOP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
ECMP_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
ECMP_SELECT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_NEXTHOP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_ECMP_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
OUTER_ECMP_SELECT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
LAG_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
LAG_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
LAG_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
LAG_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INGRESS_MAC_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INGRESS_IPV4_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INGRESS_IPV6_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INGRESS_L7_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
EGRESS_MAC_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
EGRESS_IPV4_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
EGRESS_IPV6_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
INGRESS_IP_DTEL_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
DTEL_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
DTEL_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
DTEL_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SFC_TUNNEL_NETWORK_SAP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SFC_TUNNEL_OUTER_EXM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SFC_TUNNEL_OUTER_TCAM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SFC_TUNNEL_INNER_EXM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SFC_TUNNEL_INNER_TCAM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SFC_SF_SEL_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SFC_SF_SEL_NSH_XLATE_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_0_BAS_ADV_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_0_BAS_ADV_POLICY_L3_LEN_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_0_BAS_ADV_POLICY_L4_SRC_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_0_BAS_ADV_POLICY_L4_DST_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_0_SFP_FLW_CLS_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_0_SFP_SCHD_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_0_SFP_SCHD_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_0_SFP_SCHD_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_0_SFP_SCHD_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SFF_ARP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_1_MULTICAST_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_ING_SF_1_MULTICAST_RID_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_POLICY_L3_LEN_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_SRC_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_DST_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_HDR_STRIP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_TRUNC_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
NPB_EGR_SFF_ARP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
DEDUP_NUM_BLOCKS_PIPELINE_NPB_IGONLY_EGONLY_IGONLY, \
DEDUP_ADDR_WIDTH_PIPELINE_NPB_IGONLY_EGONLY_IGONLY 

// Deployment Profile: egOnly
// -----------------------------------------------

const bool TRANSPORT_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_IPV4_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_IPV4_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_IPV6_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_IPV6_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_IPV6_REDUCED_ADDR_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_GRE_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_GRE_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_ERSPAN_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_ERSPAN_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_ERSPAN_INGRESS_SET_TUNNEL_ID_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool TRANSPORT_IPV4_VXLAN_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_IPV4_GENEVE_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool TRANSPORT_SPBM_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool TRANSPORT_EoMPLS_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool TRANSPORT_IPoMPLS_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool OUTER_ETAG_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool OUTER_VNTAG_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool OUTER_EoMPLS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool OUTER_EoMPLS_PWCW_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool OUTER_IPoMPLS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool OUTER_MPLSoGRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool OUTER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool OUTER_IPINIP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool OUTER_GENEVE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool OUTER_VXLAN_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool OUTER_NVGRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool OUTER_GRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool OUTER_GTP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool INNER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool INNER_IPINIP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool INNER_GRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool INNER_GTP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool INNER_INNER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bool UDF_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool FOLDED_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = false;
const bool EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = true;
const bit<32> MPLS_DEPTH_TRANSPORT_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 4;
const bit<32> MPLS_DEPTH_OUTER_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 4;
const bit<32> PORT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 288;
const bit<32> VLAN_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 4096;
const bit<32> PORT_VLAN_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> BD_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 5120;
const bit<32> RMAC_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 64;
const bit<32> MAC_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> IPV4_DST_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> IPV4_SRC_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 256;
const bit<32> IPV6_DST_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> IPV6_SRC_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 256;
const bit<32> TUNNEL_SRC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 512;
const bit<32> TUNNEL_DST_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> TUNNEL_SMAC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 32;
const bit<32> TUNNEL_DMAC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 256;
const bit<32> NEXTHOP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8192;
const bit<32> ECMP_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> ECMP_SELECT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 16384;
const bit<32> OUTER_NEXTHOP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 4096;
const bit<32> OUTER_ECMP_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 4096;
const bit<32> OUTER_ECMP_SELECT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 16384;
const bit<32> LAG_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> LAG_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 32;
const bit<32> LAG_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 64;
const bit<32> LAG_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 2048;
const bit<32> INGRESS_MAC_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1536;
const bit<32> INGRESS_IPV4_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 6144;
const bit<32> INGRESS_IPV6_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 2048;
const bit<32> INGRESS_L7_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> EGRESS_MAC_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 2048;
const bit<32> EGRESS_IPV4_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 6144;
const bit<32> EGRESS_IPV6_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 2048;
const bit<32> INGRESS_IP_DTEL_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 512;
const bit<32> DTEL_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 4;
const bit<32> DTEL_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 64;
const bit<32> DTEL_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 256;
const bit<32> NPB_ING_SFC_TUNNEL_NETWORK_SAP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8192;
const bit<32> NPB_ING_SFC_TUNNEL_OUTER_EXM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8192;
const bit<32> NPB_ING_SFC_TUNNEL_OUTER_TCAM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> NPB_ING_SFC_TUNNEL_INNER_EXM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8192;
const bit<32> NPB_ING_SFC_TUNNEL_INNER_TCAM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 2048;
const bit<32> NPB_ING_SFC_SF_SEL_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8192;
const bit<32> NPB_ING_SFC_SF_SEL_NSH_XLATE_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8192;
const bit<32> NPB_ING_SF_0_BAS_ADV_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> NPB_ING_SF_0_BAS_ADV_POLICY_L3_LEN_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 128;
const bit<32> NPB_ING_SF_0_BAS_ADV_POLICY_L4_SRC_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 256;
const bit<32> NPB_ING_SF_0_BAS_ADV_POLICY_L4_DST_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 256;
const bit<32> NPB_ING_SF_0_SFP_FLW_CLS_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 128;
const bit<32> NPB_ING_SF_0_SFP_SCHD_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8192;
const bit<32> NPB_ING_SF_0_SFP_SCHD_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 128;
const bit<32> NPB_ING_SF_0_SFP_SCHD_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 128;
const bit<32> NPB_ING_SF_0_SFP_SCHD_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 16384;
const bit<32> NPB_ING_SFF_ARP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8192;
const bit<32> NPB_ING_SF_1_MULTICAST_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 1024;
const bit<32> NPB_ING_SF_1_MULTICAST_RID_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 2096;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8192;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_POLICY_L3_LEN_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 128;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_SRC_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 256;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_DST_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 256;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_HDR_STRIP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8;
const bit<32> NPB_EGR_SF_2_EGRESS_SFP_TRUNC_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8;
const bit<32> NPB_EGR_SFF_ARP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 8192;
const bit<32> DEDUP_NUM_BLOCKS_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 16;
const bit<32> DEDUP_ADDR_WIDTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY = 16;

// Use this #define to pass the list of deployment
// params into your top-level module instantiations.
#define INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY_EGONLY_EGONLY \
TRANSPORT_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_IPV4_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_IPV4_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_IPV6_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_IPV6_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_IPV6_REDUCED_ADDR_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_GRE_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_GRE_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_ERSPAN_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_ERSPAN_EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_ERSPAN_INGRESS_SET_TUNNEL_ID_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_IPV4_VXLAN_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_IPV4_GENEVE_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_SPBM_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_EoMPLS_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TRANSPORT_IPoMPLS_INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_ETAG_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_VNTAG_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_EoMPLS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_EoMPLS_PWCW_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_IPoMPLS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_MPLSoGRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_IPINIP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_GENEVE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_VXLAN_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_NVGRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_GRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_GTP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INNER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INNER_IPINIP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INNER_GRE_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INNER_GTP_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INNER_INNER_IPV6_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
UDF_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
FOLDED_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
EGRESS_ENABLE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
MPLS_DEPTH_TRANSPORT_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
MPLS_DEPTH_OUTER_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
PORT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
VLAN_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
PORT_VLAN_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
BD_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
RMAC_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
MAC_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
IPV4_DST_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
IPV4_SRC_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
IPV6_DST_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
IPV6_SRC_TUNNEL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TUNNEL_SRC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TUNNEL_DST_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TUNNEL_SMAC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
TUNNEL_DMAC_REWRITE_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NEXTHOP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
ECMP_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
ECMP_SELECT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_NEXTHOP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_ECMP_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
OUTER_ECMP_SELECT_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
LAG_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
LAG_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
LAG_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
LAG_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INGRESS_MAC_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INGRESS_IPV4_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INGRESS_IPV6_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INGRESS_L7_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
EGRESS_MAC_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
EGRESS_IPV4_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
EGRESS_IPV6_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
INGRESS_IP_DTEL_ACL_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
DTEL_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
DTEL_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
DTEL_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SFC_TUNNEL_NETWORK_SAP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SFC_TUNNEL_OUTER_EXM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SFC_TUNNEL_OUTER_TCAM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SFC_TUNNEL_INNER_EXM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SFC_TUNNEL_INNER_TCAM_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SFC_SF_SEL_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SFC_SF_SEL_NSH_XLATE_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_0_BAS_ADV_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_0_BAS_ADV_POLICY_L3_LEN_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_0_BAS_ADV_POLICY_L4_SRC_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_0_BAS_ADV_POLICY_L4_DST_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_0_SFP_FLW_CLS_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_0_SFP_SCHD_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_0_SFP_SCHD_GROUP_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_0_SFP_SCHD_MAX_MEMBERS_PER_GROUP_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_0_SFP_SCHD_SELECTOR_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SFF_ARP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_1_MULTICAST_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_ING_SF_1_MULTICAST_RID_TABLE_SIZE_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_SFF_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_POLICY_L3_LEN_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_SRC_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_POLICY_L4_DST_RNG_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_HDR_STRIP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_EGR_SF_2_EGRESS_SFP_TRUNC_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
NPB_EGR_SFF_ARP_TABLE_DEPTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
DEDUP_NUM_BLOCKS_PIPELINE_NPB_IGONLY_EGONLY_EGONLY, \
DEDUP_ADDR_WIDTH_PIPELINE_NPB_IGONLY_EGONLY_EGONLY 

#endif // _DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY_EGONLY_