#!/bin/bash

fast=false;

shopt -s nullglob

TRY_GLSC="
    $HOME/p4c-tofino/shell.py
    $HOME/p4c-tofino/p4c_tofino/shell.py
    $PWD/../../p4c-tofino/shell.py
    $PWD/../../p4c-tofino/p4c_tofino/shell.py
    $PWD/../submodules/p4c-tofino/shell.py
    $PWD/../submodules/p4c-tofino/p4c_tofino/shell.py
"

while expr "$1" : - >/dev/null; do
    case $1 in
    -f) fast=true
        ;;
    -s)
        TRY_GLSC="
            $PWD/../submodules/p4c-tofino/shell.py
            $PWD/../submodules/p4c-tofino/p4c_tofino/shell.py
        "
        ;;
    -*)
        echo >&2 "unknown argumnet $1"
        ;;
    esac
    shift
done

glsc_args="--placement-order ingress_before_egress --gen-csum --libpd"

trap 'exit' 2

if [ $# -eq 0 ]; then
    set *.p4
fi

rm -rf faillog.txt
FAILLOG=$(pwd -P)/faillog.txt

if [ ! -x "$GLSC" ]; then
    for f in $TRY_GLSC; do
        if [ -x $f ]; then
            GLSC=$f
            break
        fi
    done
fi

if [ -x "$GLSC" ]; then
    echo "Using $GLSC"
else
    echo >&2 "Can't find p4c-tofino executable"
    GLSC=false
fi

function findbin () {
    if [ -x "$PWD/../$1" ]; then
        echo $PWD/../$1
    elif type $1 >/dev/null 2>&1; then
        echo $1
    else
        echo >&2 "Can't find $1 executable"
        echo false
    fi
}

if [ ! -x "$TFAS" ]; then
    TFAS=$(findbin tfas)
fi
if [ ! -x "$REFLOW" ]; then
    REFLOW=$(findbin reflow)
fi
if [ ! -x "$JSON_DIFF" ]; then
    JSON_DIFF=$(findbin json_diff)
fi
if [ -z "$DIFF" ]; then
    DIFF="diff -u"
fi

pass=0
fail=0
expected_fail=0

for p4file in "$@"; do
    echo -n $p4file
    pushd $(dirname $p4file) >/dev/null
    name=$(basename $p4file .p4)
    mkdir -p $name.out
    cd $name.out
    ok=true
    if $fast && [ -r $name.tfa ]; then
        need_reflow=false
    else 
        rm -f $name.tfa
        if $GLSC --verbose 2 -vl 2 -S $glsc_args ../$name.p4 </dev/null >glsc.log 2>&1; then
            need_reflow=true
            if [ ! -r $name.tfa ]; then
                echo -n " p4 compile failed to produce asm"
                let fail++
                echo "$p4file:" >> $FAILLOG
                cat glsc.log >> $FAILLOG
                ok=false
            fi
        else
            echo -n " p4 compile failed"
            let fail++
            echo "$p4file:" >> $FAILLOG
            sed 's/^/ /' glsc.log >> $FAILLOG
            ok=false
        fi
    fi
    if $ok && $TFAS -vvvvl tfas.config.log $name.tfa >tfas.log 2>&1; then
        for f in $name.out/*.cfg.json; do
            if [ "$f" = "$name.out/regs.pipe.cfg.json" ]; then
                $JSON_DIFF -i mau $f $(basename $f)
                continue
            fi
            if $REFLOW $f >tmp.json 2>/dev/null; then
                mv tmp.json $f
            fi
            if $need_reflow && $REFLOW $(basename $f) >tmp.json 2>/dev/null; then
                mv tmp.json $(basename $f)
            fi
            $DIFF $f $(basename $f)
        done > json_diff.txt
        if [ -r $name.out/tbl-cfg ]; then
            $JSON_DIFF -dl handle -i table_type ${name}_context_llir.json $name.out/tbl-cfg >> json_diff.txt
        fi
        cnt=$(grep -Ev '^\+\+\+|^---|"int_inj"' json_diff.txt | grep -Ec '^\+|^-')
        if [ $cnt -gt 0 ]; then
            echo -n " mismatch"
            let fail++
            echo "$p4file:" >> $FAILLOG
            cat json_diff.txt >> $FAILLOG
        else
            echo -n " pass"
            let pass++
        fi
    elif $ok; then
        echo -n " tfas failed"
        let fail++
        echo "$p4file:" >> $FAILLOG
        sed 's/^/ /' tfas.log >> $FAILLOG
        ok=false
        if $need_reflow; then
            # we ran the compiler and tfas failed, so reflow the compiler outputs
            # so that later -f runs will work
            for f in *.json; do
                if $REFLOW $f >tmp.json 2>/dev/null; then
                    mv tmp.json $f
                fi
            done
        fi
    fi
    if grep -qs "^$name.p4" ../expected_failures.txt; then
        if $ok; then
            echo " (UNEXPECTED PASS)"
        else
            echo " (expected)"
            let expected_fail++
        fi
    else
        echo
    fi
    popd >/dev/null
done

echo "$pass tests passed, $fail tests fail"

if [ $fail -ne $expected_fail ]; then
    exit 1
fi
