#ifndef BF_P4C_ARCH_FROMV1_0_ADD_METADATA_PARSER_STATES_H_
#define BF_P4C_ARCH_FROMV1_0_ADD_METADATA_PARSER_STATES_H_

#include "ir/ir.h"

namespace P4 {
class ReferenceMap;
class TypeMap;
}

namespace BFN {

/// Add parser states to parse ingress and egress intrinsic metadata generated by Tofino.
/// And then add parser states to parse metadata that is prepended to user packet data.
/// These are, on ingress, phase0 and resubmit metadata; And on egress, bridged and mirror metadata.
struct AddMetadataParserStates : PassManager {
    AddMetadataParserStates(P4::ReferenceMap* refMap, P4::TypeMap* typeMap);
};

}  // namespace BFN

#endif  /* BF_P4C_ARCH_FROMV1_0_ADD_METADATA_PARSER_STATES_H_ */
