ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN docker/jarvis_setup.sh
ENV CC "distcc gcc"
ENV CXX "distcc g++"

COPY --from=amr-registry.caas.intel.com/bxd-sw/bf-p4c-tools:bfp4c_static \
     /bfn/bf-p4c-tools/compilers/bf-p4c-compilers/build/p4check /p4factory/install/bin/p4check

WORKDIR /bfn/bf-p4c-compilers

# Expose port 80 for accessing Doxygen-generated documentation
EXPOSE 80

CMD ["/bin/bash"]
ENTRYPOINT ["/bfn/docker_entry_point.sh"]

