# 'amr-registry.caas.intel.com/bxd-sw' for CaaS (AMR)
ARG DOCKER_PROJECT=barefootnetworks

FROM ${DOCKER_PROJECT}/scratch:latest
COPY --from=bf-p4c-compilers_for_p4i:latest /bfn/bf-p4c-compilers/scripts/gen_reference_outputs/results results
COPY --from=bf-p4c-compilers_for_p4i:latest /bfn/bf-p4c-compilers/scripts/gen_reference_outputs/README results
