/****************************************************************************** 
 * Default ULL Profile 
 *****************************************************************************/ 

#define IPSG_DISABLE 
#define MPLS_DISABLE 
#define URPF_DISABLE 
#define METER_DISABLE 
#define NVGRE_DISABLE 
//#define TUNNEL_DISABLE 
//#define IPV6_DISABLE 
//#define MULTICAST_DISABLE 
//#define NAT_DISABLE 
//#define L2_DISABLE 
//#define ACL_DISABLE 
//#define ACL_RANGE_DISABLE 
//#define RACL_DISABLE 
//#define QOS_DISABLE 
//#define STORM_CONTROL_DISABLE 
//#define STATS_DISABLE 
//#define MIRROR_DISABLE 

#define VALIDATE_PACKET_TABLE_SIZE 1 
#define PORTMAP_TABLE_SIZE 1 
#define STORM_CONTROL_TABLE_SIZE 1 
#define STORM_CONTROL_METER_TABLE_SIZE 1 
#define STORM_CONTROL_STATS_TABLE_SIZE 1 
#define PORT_VLAN_TABLE_SIZE 1 
#define OUTER_ROUTER_MAC_TABLE_SIZE 1 
#define DEST_TUNNEL_TABLE_SIZE 1 
#define IPV4_SRC_TUNNEL_TABLE_SIZE 1 
#define IPV6_SRC_TUNNEL_TABLE_SIZE 1 
#define TUNNEL_SRC_REWRITE_TABLE_SIZE 1 
#define TUNNEL_DST_REWRITE_TABLE_SIZE 1 
#define OUTER_MULTICAST_STAR_G_TABLE_SIZE 1 
#define OUTER_MULTICAST_S_G_TABLE_SIZE 1 
#define VNID_MAPPING_TABLE_SIZE 1 
#define BD_TABLE_SIZE 1 
#define BD_FLOOD_TABLE_SIZE 1 
#define BD_STATS_TABLE_SIZE 1 
#define OUTER_MCAST_RPF_TABLE_SIZE 1 
#define MPLS_TABLE_SIZE 1 
#define VALIDATE_MPLS_TABLE_SIZE 1 

#define ROUTER_MAC_TABLE_SIZE 1 
#define MAC_TABLE_SIZE 1 
#define IPSG_TABLE_SIZE 1 
#define IPSG_PERMIT_SPECIAL_TABLE_SIZE 1 
#define INGRESS_MAC_ACL_TABLE_SIZE 1 
#define INGRESS_IP_ACL_TABLE_SIZE 1 
#define INGRESS_IPV6_ACL_TABLE_SIZE 1 
#define EGRESS_MAC_ACL_TABLE_SIZE 1 
#define EGRESS_IP_ACL_TABLE_SIZE 1 
#define EGRESS_IPV6_ACL_TABLE_SIZE 1 
#define INGRESS_IP_RACL_TABLE_SIZE 1 
#define INGRESS_IPV6_RACL_TABLE_SIZE 1 
#define IP_NAT_TABLE_SIZE 1 
#define IP_NAT_FLOW_TABLE_SIZE 1 
#define EGRESS_NAT_TABLE_SIZE 1 
#define UPDATE_L4_CHECKSUM_TABLE_SIZE 1 

#define IPV4_LPM_TABLE_SIZE 1 
#define IPV6_LPM_TABLE_SIZE 1 
#define IPV4_HOST_TABLE_SIZE 1 
#define IPV6_HOST_TABLE_SIZE 1 

#define IPV4_MULTICAST_STAR_G_TABLE_SIZE 1 
#define IPV4_MULTICAST_S_G_TABLE_SIZE 1 
#define IPV6_MULTICAST_STAR_G_TABLE_SIZE 1 
#define IPV6_MULTICAST_S_G_TABLE_SIZE 1 
#define MCAST_RPF_TABLE_SIZE 1 

#define FWD_RESULT_TABLE_SIZE 1 
#define URPF_GROUP_TABLE_SIZE 1 
#define ECMP_GROUP_TABLE_SIZE 1 
#define ECMP_SELECT_TABLE_SIZE 1 
#define WCMP_GROUP_TABLE_SIZE 1 
#define NEXTHOP_TABLE_SIZE 1 
#define LAG_GROUP_TABLE_SIZE 1 
#define LAG_SELECT_TABLE_SIZE 1 
#define SYSTEM_ACL_SIZE 1 
#define LEARN_NOTIFY_TABLE_SIZE 1 

#define MAC_REWRITE_TABLE_SIZE 1 
#define EGRESS_VNID_MAPPING_TABLE_SIZE 1 
#define EGRESS_BD_MAPPING_TABLE_SIZE 1 
#define EGRESS_BD_STATS_TABLE_SIZE 1 
#define REPLICA_TYPE_TABLE_SIZE 1 
#define RID_TABLE_SIZE 1 
#define TUNNEL_DECAP_TABLE_SIZE 1 
#define L3_MTU_TABLE_SIZE 1 
#define EGRESS_VLAN_XLATE_TABLE_SIZE 1 
#define SPANNING_TREE_TABLE_SIZE 1 
#define FABRIC_REWRITE_TABLE_SIZE 1 
#define EGRESS_ACL_TABLE_SIZE 1 
#define INGRESS_ACL_RANGE_TABLE_SIZE 1 
#define EGRESS_ACL_RANGE_TABLE_SIZE 1 
#define VLAN_DECAP_TABLE_SIZE 1 
#define TUNNEL_HEADER_TABLE_SIZE 1 
#define TUNNEL_REWRITE_TABLE_SIZE 1 
#define TUNNEL_SMAC_REWRITE_TABLE_SIZE 1 
#define TUNNEL_DMAC_REWRITE_TABLE_SIZE 1 

#define MIRROR_SESSIONS_TABLE_SIZE 1 
#define MIRROR_COALESCING_SESSIONS_TABLE_SIZE 1 

#define DROP_STATS_TABLE_SIZE 1 
#define ACL_STATS_TABLE_SIZE 1 
#define METER_INDEX_TABLE_SIZE 1 
#define METER_ACTION_TABLE_SIZE 1 

#define INT_TERMINATE_TABLE_SIZE 1 
#define INT_SOURCE_TABLE_SIZE 1 
#define INT_UNDERLAY_ENCAP_TABLE_SIZE 1 
#define PLT_HASH_WIDTH 1 
#define PLT_BLOOM_FILTER_SIZE 1 
#define PLT_NUM_FILTERS 1 

#define INGRESS_QOS_MAP_TABLE_SIZE 1 
#define EGRESS_QOS_MAP_TABLE_SIZE 1 
#define QUEUE_TABLE_SIZE 1 
#define DSCP_TO_TC_AND_COLOR_TABLE_SIZE 1 
#define PCP_TO_TC_AND_COLOR_TABLE_SIZE 1 

#define SFLOW_INGRESS_TABLE_SIZE 1 
#define SFLOW_EGRESS_TABLE_SIZE 1 
#define MAX_SFLOW_SESSIONS 1 

#define MAX_BFD_SESSIONS 1 
#define MAX_BFD_SESSIONS_PER_PIPE 1 
#define MAX_BFD_SESSIONS_PER_PIPE_2X 1 
#define BFD_TX_TIMER_TABLE_SIZE 1 

#define FLOWLET_MAP_SIZE 1 
#define FLOWLET_MAP_WIDTH 1 

#define LAG_FAILOVER_TABLE_SIZE 1 
#define ECMP_FAILOVER_TABLE_SIZE 1 
#define LAG_FAILOVER_REG_INSTANCE_COUNT 1 
#define ECMP_FAILOVER_REG_INSTANCE_COUNT 1 

#define COPP_METER_TABLE_SIZE 1 
#define COPP_TABLE_SIZE 1 

#define EGRESS_PORT_LKP_FIELD_SIZE 1 

#define ADJUST_PACKET_LENGTH_TABLE_SIZE 1 
