#! /bin/bash

if [ $# -lt 2 ]; then
   echo "Usage: $0  <input_file> <output_file>"
      exit 1
      fi

bindir=$(dirname $(realpath $0))
incdir=$(realpath $bindir/../share/p4c)
export P4C_16_INCLUDE_PATH=$incdir/p4include
export P4C_14_INCLUDE_PATH=$incdir/p4_14include
infile=$1
outfile=$2
shift
shift

$bindir/p4c-barefoot --std=p4-14 --Wdisable -o /dev/null \
                     --target tofino --arch tna \
                     --pp $outfile $infile $@
