#! /bin/bash

# Copyright (C) 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.  You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#
#
# SPDX-License-Identifier: Apache-2.0
set -x

if [ $# -lt 2 ]; then
   echo "Usage: $0  <input_file> <output_file> [arch]"
      exit 1
      fi

bindir=$(dirname $(realpath $0))
incdir=$(realpath $bindir/../share/p4c)
export P4C_16_INCLUDE_PATH=$incdir/p4include
export P4C_14_INCLUDE_PATH=$incdir/p4_14include
infile=$1
outfile=$2
arch=${3:-"v1model"}
shift
shift
shift

$bindir/p4c-barefoot --std=p4-14 --Wdisable -o /dev/null \
                     --target tofino --arch $arch \
                     --pp $outfile $infile $@
