#! /usr/bin/env python3

# Copyright (C) 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.  You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#
#
# SPDX-License-Identifier: Apache-2.0

# Script to validate a resources.json against the json schema
#
# The default behavior takes a resources.json file as a mandatory argument
# and it validates it agains the gen_schema file in the Glass repo.
#
# If used from the default location, the relative path to the Glass repo
# is automatically configured. Otherwise, please add the corresponding
# directory to PYTHONPATH
#
import os, sys
from jsonvalidator import JSONValidator

MYPATH = os.path.dirname(os.path.realpath(__file__))
GEN_SCHEMA_PATH=os.path.join(MYPATH, "../compiler_interfaces")
sys.path.append(GEN_SCHEMA_PATH)

from schemas.table_graph_schema import TableGraphsSchema, get_schema_version

v = JSONValidator()
rc = v.validate('dep.json', TableGraphsSchema, get_schema_version())
if not rc:
    sys.exit(1)
