#! /usr/bin/env python

# Script to validate the compiler manifest
#

import os, sys
from jsonvalidator import JSONValidator

MYPATH = os.path.dirname(__file__)
GEN_SCHEMA_PATH=os.path.join(MYPATH, "../glass/p4c_tofino/target/tofino/ctx_json")
sys.path.append(GEN_SCHEMA_PATH)

from archive_manifest import BFNCompilerArchive, get_schema_version

v = JSONValidator()
if not v.validate('manifest.json', BFNCompilerArchive, get_schema_version()):
    sys.exit(1)
