/**
 * Copyright (C) 2024 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.  See the License for the specific language governing permissions
 * and limitations under the License.
 *
 *
 * SPDX-License-Identifier: Apache-2.0
 */

@Library('bf-jenkins-utils@master')_

node('master') {
 stage('Determine Target Branch') {
  // The 'CHANGE_TARGET' env var is set by Jenkins and contains the value of the
  // branch the PR will be merged into if everything works well. We use this
  // variable to decide which p4factory docker image to use
  if (env.CHANGE_TARGET == null) {
     env.CHANGE_TARGET = "master"
  }

  target_branch = "${env.CHANGE_TARGET}"
 }
}

pipeline {
  agent { label 'github-pr-builder' }
  stages {
    stage('Pre processing: cleanup') {
      steps {
        script {
            stopPreviousRuns(this)
        }
      }
    }

    stage('Style Check') {
        parallel {
            stage ('Run clang-format-check.py ') {
                agent {
                    docker {
                    label 'github-pr-builder'
                        image "artifacts-bxdsw.sc.intel.com:9444/p4factory:${target_branch}"
                        registryUrl 'https://artifacts-bxdsw.sc.intel.com:9444'
                        registryCredentialsId 'nexus-docker-creds'
                        args '--privileged --cap-add=ALL  --user=root'
                        alwaysPull true
                    }
                }

              steps {
                    sh '''
                      git submodule update --init --recursive
                      python3 /p4factory/tools/clang-format-check.py -r
                    '''
                }
            }
        } // parallel
    } // stage

  }
  post {
    always {
      script {
        if (currentBuild.currentResult == 'FAILURE') { // Other values: SUCCESS, UNSTABLE
          bfEmailFromGHId(this)
        }
      }
    }
  }
}


