#ifndef _PGM_SP_NPB_IGONLY_NPB_IGONLY_NPB_IGONLY_NPB_EGONLY_TOP_
#define _PGM_SP_NPB_IGONLY_NPB_IGONLY_NPB_IGONLY_NPB_EGONLY_TOP_

#if __TARGET_TOFINO__ == 2
#include <t2na.p4>
#else
#include <tna.p4>
#endif

#define BRIDGED_METADATA_WIDTH          37 // number of bytes in the bridged metadata -- must be set manually -- can change between compiler runs

#include "p4src_includes.p4"

Pipeline(
    IngressParser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    IngressControl(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    IngressDeparser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    EgressParser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    EgressControl(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    EgressDeparser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY)) pipeline_npb_igOnly_A;

Pipeline(
    IngressParser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    IngressControl(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    IngressDeparser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    EgressParser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    EgressControl(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    EgressDeparser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY)) pipeline_npb_igOnly_B;

Pipeline(
    IngressParser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    IngressControl(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    IngressDeparser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    EgressParser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    EgressControl(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY),
    EgressDeparser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_IGONLY)) pipeline_npb_igOnly_C;

Pipeline(
    IngressParser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_EGONLY),
    IngressControl(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_EGONLY),
    IngressDeparser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_EGONLY),
    EgressParser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_EGONLY),
    EgressControl(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_EGONLY),
    EgressDeparser(INSTANCE_DEPLOYMENT_PARAMS_PIPELINE_NPB_EGONLY)) pipeline_npb_egOnly;

Switch(
    pipeline_npb_igOnly_A,
    pipeline_npb_igOnly_B,
    pipeline_npb_igOnly_C,
    pipeline_npb_egOnly
) main;

#endif // _PGM_SP_NPB_IGONLY_NPB_IGONLY_NPB_IGONLY_NPB_EGONLY_TOP_
