# Workflow for Klocwork Differential Analysis
name: Klocwork Differential Analysis

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the protected branches
  pull_request:
    types: [opened, synchronize, reopened]
  
  # Triggers the workflow on push or pull request events but only for the protected branches
  # ATTENTION ! pull_request_target trigger means that wokflow uses workflow file from target branch, not from PR branch!
  pull_request_target:
    types: [closed]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TARGET_BRANCH: ${{ startsWith(github.base_ref, 'rel_') && github.base_ref || 'master' }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  klocwork-differential-analysis:
    # Do not run KDA on closed non merged PR (merged event doesn't exist)
    if: ${{ (github.event.action == 'closed' && github.event.pull_request.merged != true) == false}}
    # The tag of runner that the job will run on
    runs-on: kda-compilers
    container:
      # For branches other than rel_* use master container. Dockerfile for kwserver container is available at: bf-docker/Dockerfile.p4factory.kwserver 
      # Docker container is created in following jenkins job: https://qa-jenkins-01-bxdsw.sc.intel.com/job/kwserver_build/
      image: artifacts-bxdsw.sc.intel.com:9444/p4factory/kwserver:${{ startsWith(github.base_ref, 'rel_') && github.base_ref || 'master' }}
      #credentials:
        #username: ${{secrets.DOCKER_USERNAME}}
        #password: ${{secrets.DOCKER_PASSWORD}}
      options: "--privileged --cap-add=ALL --user=root "

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it      
      - name: List files modified in PR
        id: list
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            const files = await github.rest.pulls.listFiles({ owner: context.repo.owner, repo: context.repo.repo, pull_number: context.issue.number});
            const file_pattern = [".cpp" , ".h", ".hpp", ".c", "CmakeLists.txt", "yml", "kw_config"]
            return files.data.map(i => i.filename).filter(file => file_pattern.some(p => file.includes(p)))
      
      - name: Check if branch exists
        if: ${{ steps.list.outputs.result != '' && github.event.pull_request.merged }}
        uses: actions/github-script@v5
        with:
          script: |
            try {
              const pr = await github.rest.pulls.get({owner:context.repo.owner, repo:context.repo.repo, pull_number: context.issue.number});
              console.log(pr)
              console.log(pr.data.head.ref)
              const branch = await github.rest.repos.getBranch({ owner: context.repo.owner, repo: context.repo.repo, branch: pr.data.head.ref});
            } catch (HttpError) {
              // Restore branch to save KDA results
              const new_branch = await github.rest.git.createRef({ owner: context.repo.owner, repo: context.repo.repo, ref:'refs/heads/'.concat('${{github.head_ref}}'), sha: '${{github.sha}}'}); 
            }
      
      - name: Checkout code
        if: ${{ steps.list.outputs.result != '' }}
        uses: actions/checkout@v2
        
      - name: Run KDA
        if: ${{ steps.list.outputs.result != '' }}
        run: |
          # Set KW project name according to target branch
            sed -i "s/KLOCWORK_PROJECT_NAME.*/KLOCWORK_PROJECT_NAME : \"${TARGET_BRANCH}__bf-p4c-compilers\"/g" ci/kw_config
            
          # Run KDA
          python3.9 /KDA/KDA/src/main.py diff_analysis --pr_number ${{ github.event.number }} --config $GITHUB_WORKSPACE/ci/kw_config --pat ${{ secrets.GITHUB_TOKEN }}
      # Branch will be deleted after KDA scan uploads the results after merging the PR
      - name: Delete Branch on merge
        if: ${{ github.event.pull_request.merged }}
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.git.deleteRef({ owner: context.repo.owner, repo: context.repo.repo, ref:'heads/'.concat('${{github.head_ref}}')})
